### ISSUE TITLE
Use from App Delegate

### ISSUE THREAD

**Issue by ghost** [rjeprasad/RappleProgressHUD#10]
Hi, really cool work - thank you!

I don't have a real issue, more a question.

How would you go about showing RappleProgressHUD from the app's AppDelegate?

It's possible to call, e.g.

RappleActivityIndicatorView.startAnimatingWithLabel("Processing...")

from didFinishLaunchingWithOptions function but nothing shows up...

**Comment by rjeprasad** [comment]
You can open RappleActivityIndicatorView from anywhere, including AppDelegate. But you must have at least a loaded ViewController, Coz ActivityIndicator loads on the top most loaded view controller. 'didFinishLaunchingWithOptions' method will not have a ViewController. But you can try delayed start so your app will have time to load the first ViewController.

    DispatchQueue.main.asyncAfter(deadline: .now() + 1.0, execute: { 
        RappleActivityIndicatorView.startAnimatingWithLabel("Processing...")
    })

this may work only if your delay of long enough.
