### ISSUE TITLE
xCode 9 / Swift 4 issues...

### ISSUE THREAD

**Issue by KMessina1** [rjeprasad/RappleProgressHUD#13]
![screen shot 2017-09-23 at 5 38 43 pm](https://user-images.githubusercontent.com/8019251/30777330-2bfcbf44-a086-11e7-9b73-1a44bae14cc0.png)

**Comment by dhaval4gvm** [comment]
@KMessina1  I am getting this errors too, have you found any solution?

**Comment by rjeprasad** [comment]
Can you make sure that you are using RappleProgressHUD v3.0.4 with swift 4.2 version. if you are still using swift 4.0 then you have to use  RappleProgressHUD (2.4.1). 

for swift 4 use 
pod 'RappleProgressHUD', '2.4.1'

**Comment by dhaval4gvm** [comment]
Thanks for the reply, I have updated my Xcode to Xcode 10, so now I have latest swift version i.e 4.2. So it solves my problem.

**Comment by rjeprasad** [comment]
Yes, latest pod works only with swift v4.2. Please make sure all your projects with this pod uses the proper swift version.

<img width="891" alt="screen shot 2018-10-01 at 2 51 44 pm" src="https://user-images.githubusercontent.com/13247691/46280461-94a78c80-c589-11e8-9ed0-50cf93fb792b.png">
