### ISSUE TITLE
stopAnimating with completion

### ISSUE THREAD

**Issue by nicchong** [rjeprasad/RappleProgressHUD#3]
Hi,

RappleActivityIndicatorView.stopAnimating(showCompletion: true, completionLabel: "Completed.", completionTimeout: 2.0) get "argument passed to call that takes no arguements". Any idea ?

**Comment by rjeprasad** [comment]
Hi nicchong,

I have just tested and didn't find any issue in this method.

Both
 `RappleActivityIndicatorView.stopAnimating(showCompletion: true, completionLabel: "Completed.", completionTimeout: 1.0)`
and 
`RappleActivityIndicatorView.stopAnimating()`

methods working properly.

Please check out this sample app for more details.
https://github.com/rjeprasad/PodUsageApp

Please make sure that you are using SDK 10 with Xcode 8 to run this Pod version 2.0.4.

**Comment by nicchong** [comment]
Problem fixed after pod update :)

Thanks !
