### ISSUE TITLE
completion handler two icons when completionHandler is not success.

### ISSUE THREAD

**Issue by Miramas** [rjeprasad/RappleProgressHUD#7]
thanks for the update, but it works with some bug. two icons shows up on the spinner. See the screenshot attached. 
![simulator screen shot mar 7 2017 11 36 27 am](https://cloud.githubusercontent.com/assets/11044506/23643214/79b49850-032a-11e7-8f3f-d7ef11753e3e.png)

**Comment by Miramas** [comment]
I tried to increase completionTimeout: 4.0 and it shows correctly for first two seconds, but then new completion appears, with the label of previous HUD

**Comment by rjeprasad** [comment]
UI bug that cause this issue is fixed.
