### ISSUE TITLE
Swift Compiler Warnings: 'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

### ISSUE THREAD

**Issue by PascalHuijsmans** [rjeprasad/RappleProgressHUD#9]
Hi, 

First of all: Thank you for sharing the package, it's real nice.

After I updated xcode to version 8.3.1, I getting some compiler warnings when using 2.2.7 of your package.

Xcode gives me the following warnings: 'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

The warnings are located in the RappleActivityIndicatorView extension file on lines: 213, 217, 275 and 322.

**Comment by rjeprasad** [comment]
updated.
